name: speed_controller
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: "0.7.0"
  geoflutterfire: ^2.2.2
  geolocator: ^6.2.1
  google_maps_flutter: ^2.0.4
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.1
  get: ^4.1.4
  geocoder: ^0.2.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: raleway
       fonts:
         - asset: fonts/raleway.ttf

     - family: lato
       fonts:
         - asset: fonts/lato.ttf
